version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rafaul
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    image: techshare:1.0
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_USERNAME: root
      DB_PASSWORD: rafaul
      DB_NAME: postgres
      DB_PORT: 5432
      NODE_ENV: production
    depends_on:
      - postgres
    restart: unless-stopped
# Volúmenes
volumes:
  postgres_data:
    name: techshare
